name: Deploy Scrapper (CI/CD)

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de lancer le workflow manuellement depuis l'UI GitHub

env:
  SERVICE_NAME: v-lille-scrapper
  REGION: europe-west1
  PROJECT_ID: dash-vlille                
  REPO_NAME: cloud-run-source-deploy    
  IMAGE_NAME: v-lille-scrapper    
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Evite de cloner tout l'historique Git

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      # Define a unique image tag (e.g., using the commit SHA)
      - name: Set image tag
        run: echo "IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_TAG -f ./prod/scrape_data/scrapy_docker_img.dockerfile ./prod/scrape_data          
      - name: Push Docker image to Artifact Registry
        run: docker push $IMAGE_TAG
        
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: ${{ env.IMAGE_TAG }} # <--- Use the --image flag
          service: v-lille-scrapper
          region: ${{ env.REGION }}
          env_vars: |
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            BIGQUERY_DATASET_ID=${{ secrets.BIGQUERY_DATASET_ID }}
            BIGQUERY_TABLE_ID=${{ secrets.BIGQUERY_TABLE_ID }}
          labels: "managed-by=github-actions,commit-sha=${{ github.sha }}"
